services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nowo\SlideToConfirmBundle\Twig\NowoSlideToConfirmTwigExtension:
    tags: [twig.extension]

  Nowo\SlideToConfirmBundle\Profile\SlideToConfirmProfileRegistry:
    arguments:
      $defaultProfile: '%nowo_slide_to_confirm.default_profile%'
      $profiles: '%nowo_slide_to_confirm.profiles%'

  Nowo\SlideToConfirmBundle\Form\Type\SlideToConfirmType:
    arguments:
      $translationDomain: '%nowo_slide_to_confirm.translation_domain%'
      $debug: '%nowo_slide_to_confirm.debug%'
    tags: [form.type]

  Nowo\SlideToConfirmBundle\Form\Type\SwipeToSubmitType:
    arguments:
      $translationDomain: '%nowo_slide_to_confirm.translation_domain%'
      $debug: '%nowo_slide_to_confirm.debug%'
    tags: [form.type]
